# Generated by Django 5.1.7 on 2025-03-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rohii', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rohii',
            name='branch',
            field=models.CharField(max_length=50),
        ),
    ]
